# Generated by Django 5.0.3 on 2025-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fruits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
                ("description", models.CharField(default="", max_length=400)),
                ("image", models.ImageField(upload_to="media/fruit/")),
                ("stock", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
