# Generated by Django 5.0.3 on 2025-03-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
